# Mode 3: CLI — GitHub Copilot CLI
#
# GitHub Copilot CLI is a terminal-native AI coding agent,
# similar to Claude Code but built by GitHub.
#
# ------------------------------------------------------------
# SETUP (one-time, after GitHub Education / Copilot is approved)
# ------------------------------------------------------------
#
#   Prerequisites: Node.js 22+ and an active GitHub Copilot subscription
#
#   Install:
#     npm install -g @github/copilot
#
#   Launch:
#     copilot
#
# ------------------------------------------------------------
# USAGE inside a Copilot CLI session
# ------------------------------------------------------------
#
#   Once inside the session, just type in plain English:
#
#     > Read sample.csv and create a bar chart saved as mode3.png
#
#   Copilot CLI will:
#     - read the file directly (no copy-paste needed)
#     - write the Python code
#     - run it
#     - save mode3.png
#
#   Useful slash commands:
#     /plan    → ask Copilot to plan before writing code
#     /model   → switch between Claude, GPT, etc.
#     /help    → see all available commands
#
# ------------------------------------------------------------
# Key insight
# ------------------------------------------------------------
#
#   Mode 1 (Gemini):      you copy-paste data IN, copy-paste code OUT
#   Mode 2 (Copilot IDE): Copilot sees your files; inserts code into editor
#   Mode 3 (Copilot CLI): Copilot sees your files, writes AND runs code
#                          — entirely from the terminal, no GUI needed
#
# ------------------------------------------------------------
# This file is your scratchpad.
# Paste any code generated by Copilot CLI here if needed,
# then run:  python mode3.py
# ------------------------------------------------------------

